lernparadies_lernparadies_blog:
    resource: "@LernparadiesBlogBundle/Resources/config/routing.yml"
    prefix:   /

lernparadies_lernparadies:
    resource: "@LernparadiesLernparadiesBundle/Resources/config/routing.yml"
    prefix:   /

lernparadies_vokali:
    resource: "@LernparadiesVokaliBundle/Resources/config/routing.yml"
    prefix:   /

lernparadies_benutzer:
    resource: "@LernparadiesBenutzerBundle/Resources/config/routing.yml"
    prefix:   /