vokabel:
    pattern:  /
    defaults: { _controller: "LernparadiesVokaliBundle:Vokabel:index" }

vokabel_show:
    pattern:  /{id}/show
    defaults: { _controller: "LernparadiesVokaliBundle:Vokabel:show" }

vokabel_new:
    pattern:  /new/{lang1}/{lang2}
    defaults: { _controller: "LernparadiesVokaliBundle:Vokabel:new" }

vokabel_create:
    pattern:  /create
    defaults: { _controller: "LernparadiesVokaliBundle:Vokabel:create" }
    requirements: { _method: post }

vokabel_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "LernparadiesVokaliBundle:Vokabel:edit" }

vokabel_update:
    pattern:  /{id}/update
    defaults: { _controller: "LernparadiesVokaliBundle:Vokabel:update" }
    requirements: { _method: post|put }

vokabel_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "LernparadiesVokaliBundle:Vokabel:delete" }
    requirements: { _method: post|delete }
